[package]
authors = ["The Cranelift Project Developers"]
description = "Toy language implemented using cranelift-jit"
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
name = "cranelift-jit-demo"
repository = "https://github.com/bytecodealliance/cranelift-jit-demo"
version = "0.0.0"

[dependencies]
anyhow = "1.0.43"
cranelift = "0.69.0"
cranelift-jit = "0.69.0"
cranelift-module = "0.69.0"
non-empty-vec = "0.2.0"
peg = "0.7"
thiserror = "1.0.29"
